Updating jar

diff --git a/.github/workflows/deploy-backend.yml b/.github/workflows/deploy-backend.yml
--- a/.github/workflows/deploy-backend.yml
+++ b/.github/workflows/deploy-backend.yml
@@ -60,7 +60,17 @@ jobs:
             # sudo systemctl enable backend-app.service
 
             echo "Stopping old backend service (if running)..."
-            (set +e; pkill -f 'demo-deploy-0.0.1-SNAPSHOT.jar'; ) || echo "No old process running"
+            if pkill -f 'demo-deploy-0.0.1-SNAPSHOT.jar'; then
+                echo "Old backend app killed successfully."
+            else
+                CODE=$?
+                if [ $CODE -eq 1 ]; then
+                    echo "No matching backend process was found."
+                else
+                    echo "pkill returned unexpected error code $CODE"
+                    # optionally fail the script: exit $CODE
+                fi
+            fi
             sleep 10
             /usr/bin/java -jar /home/ec2-user/demo-deploy-0.0.1-SNAPSHOT.jar
 
